#[derive(Debug, Clone)]
pub struct ToolDefinition {
    pub name: &'static str,
    pub category: &'static str,
    pub purpose: &'static str,
    pub output_format: &'static str,
    pub core: bool,
    pub safe_usage: &'static str,
}

pub fn registry() -> Vec<ToolDefinition> {
    vec![
        ToolDefinition {
            name: "subfinder",
            category: "core-discovery",
            purpose: "Passive subdomain enumeration",
            output_format: "JSONL or text",
            core: true,
            safe_usage: "Prefer passive mode and preserve source attribution.",
        },
        ToolDefinition {
            name: "amass",
            category: "core-discovery",
            purpose: "Deep asset and subdomain discovery",
            output_format: "JSON, graph, text",
            core: true,
            safe_usage: "Start with passive collection before enabling active capabilities.",
        },
        ToolDefinition {
            name: "assetfinder",
            category: "core-discovery",
            purpose: "Lightweight subdomain discovery",
            output_format: "text",
            core: true,
            safe_usage: "Treat results as candidates until validated.",
        },
        ToolDefinition {
            name: "findomain",
            category: "core-discovery",
            purpose: "Fast subdomain enumeration",
            output_format: "text",
            core: true,
            safe_usage: "Normalize results before merging them into shared datasets.",
        },
        ToolDefinition {
            name: "httpx",
            category: "live-host-probing",
            purpose: "HTTP service validation and metadata capture",
            output_format: "JSONL",
            core: true,
            safe_usage: "Use conservative probes and stay inside approved hosts.",
        },
        ToolDefinition {
            name: "dnsx",
            category: "dns-mapping",
            purpose: "DNS resolution and relationship mapping",
            output_format: "JSONL",
            core: true,
            safe_usage: "Use conservative DNS rate limits and only resolve validated scope targets.",
        },
        ToolDefinition {
            name: "gowitness",
            category: "visual-mapping",
            purpose: "Screenshots and visual application mapping",
            output_format: "screenshots plus JSONL",
            core: false,
            safe_usage: "Screenshots still touch target systems, so they must obey program rules and scope restrictions.",
        },
        ToolDefinition {
            name: "WhatWeb",
            category: "tech-fingerprinting",
            purpose: "Technology fingerprinting and basic stack labeling",
            output_format: "JSON",
            core: false,
            safe_usage: "Keep aggression low and thread counts conservative to avoid intrusive behavior.",
        },
        ToolDefinition {
            name: "katana",
            category: "crawling",
            purpose: "Modern crawler for route discovery",
            output_format: "JSONL",
            core: true,
            safe_usage: "Keep crawl depth and rate under control.",
        },
        ToolDefinition {
            name: "gau",
            category: "historical-urls",
            purpose: "Historical URL collection",
            output_format: "JSONL or text",
            core: true,
            safe_usage: "Revalidate all historical results before further use.",
        },
        ToolDefinition {
            name: "waybackurls",
            category: "historical-urls",
            purpose: "Wayback Machine URL recovery",
            output_format: "text",
            core: false,
            safe_usage: "Archive output is a hint stream, not a truth source.",
        },
        ToolDefinition {
            name: "hakrawler",
            category: "crawling",
            purpose: "Fast stream-friendly crawler",
            output_format: "text",
            core: false,
            safe_usage: "Do not let crawl behavior drift beyond scoped hosts.",
        },
        ToolDefinition {
            name: "uro",
            category: "normalization",
            purpose: "URL deduplication and reduction",
            output_format: "text",
            core: true,
            safe_usage: "Keep raw URL archives before reducing duplicates.",
        },
        ToolDefinition {
            name: "jq",
            category: "normalization",
            purpose: "JSON and JSONL transformation",
            output_format: "JSON or JSONL",
            core: true,
            safe_usage: "Version shared jq filters to avoid schema drift.",
        },
        ToolDefinition {
            name: "gf",
            category: "normalization",
            purpose: "Pattern-based URL and parameter labeling",
            output_format: "text",
            core: false,
            safe_usage: "Treat pattern hits as prioritization hints only.",
        },
        ToolDefinition {
            name: "ffuf",
            category: "content-discovery",
            purpose: "Wordlist-based content discovery",
            output_format: "JSON, CSV, HTML, text",
            core: true,
            safe_usage: "Only run in approved active phases with conservative rate limits.",
        },
        ToolDefinition {
            name: "feroxbuster",
            category: "content-discovery",
            purpose: "Recursive content discovery",
            output_format: "JSON or text",
            core: false,
            safe_usage: "Keep recursion depth and concurrency bounded.",
        },
        ToolDefinition {
            name: "dirsearch",
            category: "content-discovery",
            purpose: "Python-based content discovery",
            output_format: "JSON, CSV, HTML, text",
            core: false,
            safe_usage: "Use only with explicit approval for active recon.",
        },
        ToolDefinition {
            name: "LinkFinder",
            category: "javascript-recon",
            purpose: "Endpoint extraction from JavaScript",
            output_format: "text or HTML",
            core: true,
            safe_usage: "Review context carefully before trusting a discovered endpoint.",
        },
        ToolDefinition {
            name: "SecretFinder",
            category: "javascript-recon",
            purpose: "Secret-like string detection in JavaScript",
            output_format: "text or HTML",
            core: false,
            safe_usage: "Handle potential secret material carefully and favor redaction.",
        },
        ToolDefinition {
            name: "JSParser",
            category: "javascript-recon",
            purpose: "JavaScript route and artifact parsing",
            output_format: "text",
            core: false,
            safe_usage: "Normalize and label results before merging them downstream.",
        },
        ToolDefinition {
            name: "naabu",
            category: "port-discovery",
            purpose: "Fast port discovery",
            output_format: "JSONL or text",
            core: false,
            safe_usage: "Only enable when the scope explicitly permits port scanning.",
        },
        ToolDefinition {
            name: "nmap",
            category: "port-discovery",
            purpose: "Service detection and deeper network metadata",
            output_format: "XML, text, grepable",
            core: false,
            safe_usage: "Use only with explicit authorization and conservative arguments.",
        },
    ]
}
